### PR TITLE
Change 'neutral' cut and fill colour so contours/labels will show

### PR DESCRIPTION
**Pull request by philipbelesky**
Suggestion: as both the labels and contours are white (and themes developed around this?) they get lost in the cut/fill mode where a large portion of the model might be in the 'neutral' state - particularly if you're only position a few items in it rather than a 1:1 copy of the mesh with the same bounds. Shifting that colour to black might be more usable?

ViewCapture20210829_183248

### CODE REVIEW

**Comment by philipbelesky** [comment]
Sorry for the pushing/closing/opening - accidentally included a few stray commits.

Also, looking at this again, having a dark gray isn't a great option as the red-ish gray and green-ish gray look similarly muddy. Perhaps a blue would work? Or, alternately, the original white but with the labels/contours as black?

**Comment by mariuszhermansdorfer** [comment]
I see your point. On the other hand, I liked using dark grey to 'mask out' the irrelevant part of the mesh and only focus on the area in of interest. White on white was a similar attempt of visually conveying the message, that this portion is done already and you can shift your attention elsewhere.

Essentially - there is only work to be done, where labels are still visible. The remaining parts, don't require user's attention any more.

On the other hand, I can see, why it can be quite confusing.

**Comment by philipbelesky** [comment]
Yea, I think the white-on-white fading is pretty intuitive. Another option might be just to hide labels that are at 0?

The key problem is probably the contour display as that information (if desired) is meaningfully limited by the white-on-white display. In other modes, it's probably idea to keep those white as I think they show up better with project. 

Perhaps as a slight compromise/stop-gap, an "Invert label/contour colors" checkbox could be added that switches between white/black? That's probably just enough control to allow for workarounds and could be desirable even if using standard analysis modes with custom colors. If that sounds good, let me know and I can update this PR to add it in.

**Comment by mariuszhermansdorfer** [comment]
Good idea, @philipbelesky. Instead of a simple checkbox, maybe we could have a slider which transitions labels' colors from white to black? We would then give users the options to work with various shades of grey rather than just a binary choice of two colors.

**Comment by philipbelesky** [comment]
Hey, just getting back into a few Sandworm things. I've updated this PR to the latest from the 2.0 branch and implemented the slider as suggested:

https://user-images.githubusercontent.com/495961/150726909-38e48977-c350-441a-b5ef-8f2674fb51a6.mp4

Let me know if it needs anything else!

**Review by mariuszhermansdorfer — APPROVED** [review]

**Pull request merged**
