### PR TITLE
Add MenuButton widget and basic layout for reset/calibrate buttons

### PR DESCRIPTION
**Pull request by philipbelesky**
Ok, I have setup the basic layout and widget. No interactivity yet. Let me know how you feel about the style/layout

Screen Shot 2022-01-31 at 6 15 05 pm
.

### CODE REVIEW

**Comment by mariuszhermansdorfer** [comment]
The button looks good! 

I'm not sure, whether 'reset' should be hidden in the dropdown menu, or kept as a default GH input as was the case before. It's used when users provide meshes for cut&fill calculations and as such, its functionality extends beyond just resetting the sliders to defaults.

**Comment by philipbelesky** [comment]
I think it makes sense to leave it as in input parameter. If it's used often for cut/fill it should be easier to access and might be useful to control programatically. I've reverted that in the latest commit and implemented the UI state; just need to check the actual action when I have access to a Kinect tomorrow.

**Comment by philipbelesky** [comment]
Ok, the functionality all seems to work as expected. One thing that might be good to bundle as part of the PR is to clarify the role of the Reset action with regard to Calibration and in general:

- At the moment Calibration only begins upon Reset, is this necessary? It might be a little unintuitive.
- Reset's tooltip states that it reverts all settings to defaults, but it acts like its more like an internal re-initialisation (e.g. buffers; sensor type; outputs) and doesn't affect the user-facing params such as `columns` or analysis settings. Should the help text be more oriented towards the use cases for this action?

**Comment by mariuszhermansdorfer** [comment]
Re. Calibration - now, that we have a dedicated button, calibration should be triggered by clicking on it. We only used 'reset' as a workaround.

Re. Reset functionality - the intended use was to have a 'panic button' which helps users when things go south for unknown reasons. It shouldn't reset any of the sliders' values since these are carefully chosen for given project's needs. It should, however, clear all internal buffers to hopefully fix any unexpected behavior. 
Please correct the tooltip text, if you can better formulate this intention.

**Comment by philipbelesky** [comment]
Ok, great. The latest two commits decouple those two actions and attempt to clarify the help text. Should be all ready for review.

**Pull request merged**
