### PR TITLE
Add basic setup model and definition

### PR DESCRIPTION
**Pull request by philipbelesky**
Not sure about the naming of file structure here, but it would be useful to have a series of reference files for use in development, just to ensure that all users are on the same page for how to work with the plugin.

### CODE REVIEW

**Comment by mariuszhermansdorfer** [comment]
What does this actually do? I am a bit unsure of why we need this?

**Comment by philipbelesky** [comment]
My thought here is that it provides a (minimal) form of documentation for how to use the plugin by providing a reference implementation. At present some of the parameters are a little unclear as to what value ranges they expect, which is difficult given they are all required to function. 

The other thought was that sometimes when working with Rhino/Grasshopper plugins it is useful to provide implementations that 'show off' what the plugin can do — i.e. tying a point cloud mesh to some analytics or using it in an unexpected manner. In these cases just providing a model seems much more simple than writing up docs.

Both of those things said, this may be a little early on both fronts. Happy to withdraw or leave the PR open until there is a proven need.

**Comment by mariuszhermansdorfer** [comment]
Agree on the need for clarity and providing robust default values for all the parameters to make SandWorm work out of the box. 
I also second showcasing the functionality in a comprehensive and attractive way. It would be great to compile a video like this:
https://www.youtube.com/watch?v=sEk2bYiXrSo

Let's leave this open for now and develop a robust core first.

**Comment by mariuszhermansdorfer** [comment]
This is very outdated, @philipbelesky. Should we close it and reopen a new one with more relevant examples reflecting the current functionality?

**Comment by philipbelesky** [comment]
Yes, will close and reconsider as part of #41

**Pull request closed without merging**
